# Generated by Django 4.0 on 2021-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
